sudo: false
language: python
python:
  - "2.7"
before_install:
  - openssl aes-256-cbc -K $encrypted_431a0956756c_key -iv $encrypted_431a0956756c_iv -in WS_DC.wsdl.enc -out primestg/data/WS_DC.wsdl -d
install:
  - "pip install -r requirements-dev.txt"
  - "pip install -e ."
script:
  - mamba
